# Generated by Django 6.0.6 on 2026-06-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('pochoclos', 'Pochoclos'), ('bebidas', 'Bebidas'), ('combos', 'Combos'), ('golosinas', 'Golosinas'), ('otros', 'Otros')], max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='candy/')),
                ('en_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
