# Generated by Django 6.0.6 on 2026-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('animacion', 'Animación'), ('ciencia_ficcion', 'Ciencia Ficción')], max_length=50)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('sinopsis', models.TextField()),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('trailer_url', models.URLField(blank=True)),
                ('en_cartelera', models.BooleanField(default=True)),
                ('fecha_estreno', models.DateField()),
            ],
        ),
    ]
