# Generated by Django 6.0.6 on 2026-06-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='formatos',
            field=models.CharField(blank=True, help_text='Ej: 2D, 3D, IMAX', max_length=200),
        ),
    ]
