# Generated by Django 6.0.6 on 2026-06-16 00:27

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_formatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='formatos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2d', '2D'), ('3d', '3D'), ('4d', '4D'), ('imax', 'IMAX'), ('dbox', 'D-BOX')], max_length=18),
        ),
    ]
