# Generated by Django 6.0.6 on 2026-06-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0003_alter_pelicula_formatos'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('2d', '2D'), ('3d', '3D'), ('4d', '4D'), ('imax', 'IMAX'), ('dbox', 'D-BOX')], default='2d', max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.PositiveIntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='peliculas.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='salas.sala')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
