# Generated by Django 6.0.6 on 2026-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Ej: Sala IMAX 1', max_length=100)),
                ('tipo', models.CharField(choices=[('estandar', 'Estándar'), ('4d', '4D'), ('imax', 'IMAX'), ('dbox', 'D-BOX'), ('premium', 'Premium')], default='estandar', max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
