# Generated by Django 6.0.6 on 2026-06-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(help_text='Ej: A, B, C', max_length=5)),
                ('numero', models.PositiveIntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='salas.sala')),
            ],
            options={
                'ordering': ['fila', 'numero'],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
