# Generated by Django 6.0.6 on 2026-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='columnas',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sala',
            name='filas',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
