# Generated by Django 6.0.6 on 2026-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_sala_columnas_sala_filas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
