# Generated by Django 6.0.6 on 2026-06-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tarjeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
