# Generated by Django 6.0.6 on 2026-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('salas', '0004_alter_sala_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.ManyToManyField(blank=True, to='salas.asiento'),
        ),
    ]
